services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk_pass
      POSTGRES_DB: helpdesk_db
    ports:
      - "5432:5432"
    volumes:
      - db_pgdata:/var/lib/postgresql/data

volumes:
  db_pgdata:
