services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk_pass
      POSTGRES_DB: helpdesk_db
    ports:
      - "5540:5432"
    volumes:
      - db_pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk_pass
      POSTGRES_DB: helpdesk_test
    ports:
      - "5541:5432"
    volumes:
      - db_test_pgdata:/var/lib/postgresql/data

volumes:
  db_pgdata:
  db_test_pgdata:
